version: '3.3'
services:
  db:
    image: mysql:latest
    volumes:
      - C:\Users\NAJCOM LAPTOP 4\Documents\database:\var\lib\mysql
    container_name: documentdb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectdb
    ports:
      - "3307:3306"


  documentservice:
    image: document
    build: .
    container_name: documentapp
    restart: always
    ports:
      - "8080:8080"
    environment:
     MYSQL_HOST: documentdb
     MYSQL_ROOT_USER: root
     MYSQL_ROOT_PASSWORD: password
     MYSQL_PORT: 3306

